### ISSUE TITLE
签到问题

### ISSUE THREAD

**Issue by Acheng-dot** [inkuang/hostloc-auto-get-points#22]
大佬 这个是用不了了吗 这几天查看action输出结果 发现在过去积分时传出了一个bad request：链接 点击后跳转到了个人的首页

**Comment by inkuang** [comment]
你是说 `400 Client Error: Bad Request for url: https://www.hostloc.com/home.php?mod=spacecp` 这个吗？  
按我之前测试的情况，这个错误一般是由于论坛开启防御导致的，一般换个时间点等论坛防御关了就正常了。  
至于这个链接，是脚本用来测试是否登录成功时访问的，也就是整个过程中第一个访问的链接，访问这个链接出现错误的话后面的过程就不会再进行了。

**Comment by inkuang** [comment]
我刚刚看了我这昨天晚上的GitHub Actions日志，签到是成功了的，我也到你fork的仓库里去看了下，昨天的定时任务也是成功了的，只是你的帐号密码错误或者根本没设置相应的环境变量，登录失败了。
另外，现在这时候论坛的防御又开了，所以你现在这时候去测试也还是会出现错误🙃

**Comment by weilining** [comment]
大佬看看我的

**Comment by Acheng-dot** [comment]
你和我一样 改下时间自己试试就好了

**Comment by inkuang** [comment]
我刚刚更新了一下代码，使用 Python 模拟 loc 的 JS 计算防 CC 的计算过程，现在应该没有问题了，你们可以更新一下试试。
