### ISSUE TITLE
未在用户设置页面找到标题，该页面可能存在错误

### ISSUE THREAD

**Issue by elunez** [inkuang/hostloc-auto-get-points#24]
当前使用 ip 地址：40.76.192.162
共检测到 1 个帐户，开始获取积分
******************************
未在用户设置页面找到标题，该页面可能存在错误！
请检查你的帐户是否正确！
******************************
程序执行完毕，获取积分过程结束

环境变量确认是正确的

**Comment by inkuang** [comment]
额，，，目前还从来没有遇到过这种情况，loc最近的经常开防御，怀疑是触发了什么奇怪的机制导致的，这个一时半会儿也没法复现🙃。

具体的这个错误的话是因为脚本会用正则提取 `https://www.hostloc.com/home.php?mod=spacecp` 这个页面的标题（`<title>` 和 `</title>` 中间的内容）来判断是否登录成功，为了防止数组越界会对是否匹配到内容进行判断，现在的情况就是没有匹配到内容，换句话说就是抓取到的页面里面没有 `title` 标签。

**Comment by cxy0105** [comment]
最近我也遇到了这个问题，检查了下发现是loc在登录地址`https://www.hostloc.com/member.php?mod=logging&action=login&loginsubmit=yes&infloat=yes&lssubmit=yes&loginhash=LkaGA&inajax=1`中增加了`loginhash`参数，在form_data里还加入了参数`formhash`。这两个参数是在进入`https://www.hostloc.com/home.php?mod=spacecp&d=1`时生成的，而且生成方式比较复杂：首次进入`https://www.hostloc.com/home.php?mod=spacecp&d=1`时先用三个随机数生成cookie`cL7=xxx`，然后跳转到`https://www.hostloc.com/home.php?mod=spacecp&d=2`才真正进入了待登录页面才能获取到`loginhash`和`formhash`

> 额，，，目前还从来没有遇到过这种情况，loc最近的经常开防御，怀疑是触发了什么奇怪的机制导致的，这个一时半会儿也没法复现。
> 
> 具体的这个错误的话是因为脚本会用正则提取 `https://www.hostloc.com/home.php?mod=spacecp` 这个页面的标题（`<title>` 和 `</title>` 中间的内容）来判断是否登录成功，为了防止数组越界会对是否匹配到内容进行判断，现在的情况就是没有匹配到内容，换句话说就是抓取到的页面里面没有 `title` 标签。

**Comment by inkuang** [comment]
> 最近我也遇到了这个问题，检查了下发现是loc在登录地址`https://www.hostloc.com/member.php?mod=logging&action=login&loginsubmit=yes&infloat=yes&lssubmit=yes&loginhash=LkaGA&inajax=1`中增加了`loginhash`参数，在form_data里还加入了参数`formhash`。这两个参数是在进入`https://www.hostloc.com/home.php?mod=spacecp&d=1`时生成的，而且生成方式比较复杂：首次进入`https://www.hostloc.com/home.php?mod=spacecp&d=1`时先用三个随机数生成cookie`cL7=xxx`，然后跳转到`https://www.hostloc.com/home.php?mod=spacecp&d=2`才真正进入了待登录页面才能获取到`loginhash`和`formhash`

我模拟的是直接在首页右上角的表单里面输入帐户密码后点击登录，这时候请求的接口是 `/member.php?mod=logging&action=login&loginsubmit=yes&infloat=yes&lssubmit=yes&inajax=1` ， 并不需要 `formhash` 参数。

至于你说的这个东西我也注意到了，但是发现只有在那个弹出的登录小窗口里面输帐户密码去登录时才会需要，这时候请求的接口是 `member.php?mod=logging&action=login&loginsubmit=yes&handlekey=login&loginhash=Lcth9&inajax=1` ，并且注意到请求接口中的 `loginhash` 是会变的（比如我这里就是 `Lcth9`，而不是你上面发的 `LkaGA`）

我感觉不太可能是登录的问题，如果真的是 loc 修改了什么，那应该所有人都是失败才对，现在这种情况只有少数几人出现（你可以点到我这个仓库的 Actions 页面去看，我的每天都成功执行了）。

另外，我上面说过这个错误提醒是由于没有在页面上匹配到 `<title>` 标签导致的，这也是很让人困惑的一点，我所有的地方都加了 `raise_for_status()` ，如果返回状态码不是200就直接抛出异常了，不会进入这个 `else` 的流程，而作为一个状态码200、正常返回的 html 页面，没有 title 标签就很奇怪，我感觉就算是拦截页面之类的也至少会有个标题吧🙃。

**Comment by inkuang** [comment]
补充：刚刚重新测试了，确认是触发了 loc 的防 cc 机制导致的，没有匹配到 `<title>` 是因为那个页面还就真没有 `<title>`  标签。
在通过登录流程后发现 cookies 为空，然后访问 `https://www.hostloc.com/home.php?mod=spacecp` 时返回了如下内容：

```
<html><body><script type="text/javascript" src="/aes.min.js" ></script><noscript><h1 style="text-align:center;color:red;"><strong>Please turn JavaScript on and reload the page.</strong></h1></noscript><script>function toNumbers(d){var e=[];d.replace(/(..)/g,function(d){e.push(parseInt(d,16))});return e}function toHex(){for(var d=[],d=1==arguments.length&&arguments[0].constructor==Array?arguments[0]:arguments,e="",f=0;f<d.length;f++)e+=(16>d[f]?"0":"")+d[f].toString(16);return e.toLowerCase()}var a=toNumbers("9cf3fba8ca5748b462115c1a7c7cb3d7"),b=toNumbers("8875b5523e55d3b62f236e48a51f3f74"),c=toNumbers("5b830849d28b8f5f4cb14b9bdc1c8d16");document.cookie="cL7="+toHex(slowAES.decrypt(c,2,a,b))+";  path=/";location.href="https://www.hostloc.com/home.php?mod=spacecp&d=1";</script></body></html>
```

**Comment by cxy0105** [comment]
对，`loginhash`和`formhash`是会变的。cookies为空返回的内容就是我说的生成cookie`cL7=xxx`那段。他这个机制还是按IP段来的怎么的

**Comment by scllen** [comment]
同样的问题
`当前使用 ip 地址：20.186.43.175
共检测到 1 个帐户，开始获取积分
******************************
未在用户设置页面找到标题，该页面可能存在错误！
请检查你的帐户是否正确！
******************************
程序执行完毕，获取积分过程结束`

**Comment by inkuang** [comment]
我刚刚更新了一下代码，使用 Python 模拟那个 JS 计算防 CC 的计算过程（其实就是一个 Cipher-Block Chaining 模式的 AES 解密，将解密结果写入特定 Cookies 值中就行了），现在应该没有问题了，你们可以更新一下试试。
