### ISSUE TITLE
考虑增加server酱推送通知吗

### ISSUE THREAD

**Issue by huchihan** [inkuang/hostloc-auto-get-points#27]
签到成功或不正常签到推送到微信提醒，这样就不用每天查看日志了啦……

**Comment by inkuang** [comment]
额，，，目前不打算加通知功能。
主要感觉这东西没什么必要，日志也不用每天去看吧，记起来了点开瞄一眼就行。就算有一段时间签到失败了也不会有什么大影响，只是一些积分而已，要是说一段时间没签到帐号会丢，那通知功能还是有必要的😂。
