### ISSUE TITLE
日志执行成功，但是积分记录里没有哎

### ISSUE THREAD

**Issue by insoxin** [inkuang/hostloc-auto-get-points#29]
什么鬼

**Comment by inkuang** [comment]
我这里一切正常啊，要点到`设置->积分->积分记录->系统奖励`中看，单纯的`设置->积分`页面确实没有访问别人空间的记录。
看那个`访问别人空间`的`最后奖励时间`是否正常就知道了，我这里是这样的（今天还没打开过loc）

动作名称 | 总次数 | 周期次数 | 威望 | 金钱 | 最后奖励时间
-- | -- | -- | -- | -- | --
访问别人空间 | 5699 | 10 | 0 | 2 | 2020-12-28 11:43
每天登录 | 602 | 1 | 1 | 2 | 2020-12-28 00:13
发表回复 | 2164 | 1 | 0 | 1 | 2020-12-25 13:12
参与投票 | 971 | 1 | 0 | 1 | 2020-12-23 19:40
